sonar.projectKey=property256
sonar.projectName=property256
sonar.projectVersion=1.0

sonar.sources=lib
sonar.sourceEncoding=UTF-8

sonar.test.exclusions=test/**/*.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/build/**
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/build/**,test/**,lib/main.dart,lib/core/routing/**,lib/core/theme/**
sonar.cpd.exclusions=**/*.g.dart,**/*.freezed.dart,**/build/**,test/**,lib/main.dart,lib/core/routing/**,lib/core/theme/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
